# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bone": "00_bone.ipynb"}

modules = ["core.py"]

doc_url = "https://lukemshepherd.github.io/PCA_2/"

git_url = "https://github.com/lukemshepherd/PCA_2/tree/master/"

def custom_doc_links(name): return None
