# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bone": "00_bone.ipynb",
         "mag": "01_maths.ipynb",
         "angle": "01_maths.ipynb",
         "quaternion_rotation_from_angle": "02_rotation.ipynb",
         "quaternion_rotation_from_quaternion": "02_rotation.ipynb",
         "rotate": "02_rotation.ipynb",
         "df_angles": "03_table.ipynb"}

modules = ["core.py"]

doc_url = "https://lukemshepherd.github.io/PCA2/"

git_url = "https://github.com/lukemshepherd/PCA2/tree/master/"

def custom_doc_links(name): return None
