# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://lukemshepherd.github.io/PCA_2_nb/"

git_url = "https://github.com/lukemshepherd/PCA_2_nb/tree/master/"

def custom_doc_links(name): return None
